# Generated by Django 2.2.14 on 2024-04-24 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 8, 44, 2, 37955)),
        ),
    ]
